apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okr-unit
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - migration-job.yaml
  - infisical-secret.yaml
  - ingress.yaml
